# Generated by Django 5.0.6 on 2024-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('hamburguer', 'Hamburguer'), ('bebida', 'Bebida'), ('molho', 'Molho'), ('porcao', 'Porção')], max_length=20),
        ),
    ]
