# Generated by Django 5.0.6 on 2024-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_cliente_options_cliente_email_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
