# Generated by Django 5.0.6 on 2024-06-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_alter_cliente_email_alter_cliente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
